# Pandas for AI/ML – Conceptual & Technical Assessment
**Module 3 · Unit 1 · Phase 1**

Name: Naga Sai Trinaya Chaluvadi

In [2]:
import numpy as np
import pandas as pd

# Section A – Output Prediction

## A – Q1. Array operations and vectorization

In [3]:
arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)

[20 40 60]
0    20
1    40
2    60
dtype: int64


**My prediction:** 

[20,40,60]

0 20

1 40

2 60

dtype:int64

**One similarity:** Both Data Structures help in performing the calculations without a loop 

**One difference:** The array doesn't have label index but series gives the index with the values and gives datatype in the output 

## A – Q2. Boolean Filtering

In [4]:
df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks']])

  Student  Marks
1       B     80
2       C     65
3       D     90


**Rows displayed:**

Student along with Marks

**Number of rows and columns:**

actual shape of df = (4,2)

output: (3,2)

**Explanation:**

The code gives the Student along with the Marks whose marks are greater than or equal to 65

**Actual Output:**
    Student  Marks

1       B     80

2       C     65

3       D     90

## A – Q3. Descriptive statistics

In [5]:
df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())

30.0
50
30.0


**My prediction (mean, max, median):**

30.0

50

30.0

**How median differs from mean:**

Mean is the average of the values which is Total Sum / Total No.Of.Values , it donot require sorted data  

Median is the middle value of a sorted data if the count of values is even then it takes the average of the middle 2 numbers 

## A – Q4. Group-wise Analysis

In [6]:
df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())

Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64


**My prediction:**

Department  

 HR            40000.0
 
 IT            50000.0
 
Name: Salary, dtype: float64


**How groupby() computes the average:**
GroupBy is used to categorize the data based on a particular column in this case it is Department so the mean is calculated for each Department 

## A – Q5. Pandas Correlation – Positive

In [7]:
df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0


**My prediction:**

1.0

**Direction and strength of the relationship:**
Direction: When the hours increase then the marks increase and vice versa
Strength: The relationship is very strong 


## A – Q6. Pandas Correlation – Negative

In [8]:
df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))

-1.0


**My prediction:**

-1.0

**What the sign indicates:**

The -ve sign indicates the direction of the relationship between Price and Demand here as the Price increases the Demand Decreases so they move in opposite direction 


# Section B – Code Correction 

## B – Q1. JSON and CSV
Objective: the CSV *has* a header row, but this code treats the first student's record as column names. Fix it.
```python
df = pd.read_csv("students.csv", header=None)
print(df)
```
(To test your fix, create a small `students.csv` in the cell below first.)

In [9]:
# Create a small test file so your corrected read_csv can run
csv_text = """ID,Name,Marks
1,Asha,80
2,Ravi,75
3,Neha,90
"""
with open("students.csv", "w") as f:
    f.write(csv_text)

In [10]:
# Corrected code
df = pd.read_csv("students.csv")
print(df)

   ID  Name  Marks
0   1  Asha     80
1   2  Ravi     75
2   3  Neha     90


**What was wrong and how I fixed it:**

header=None treated the first student's record as column names.

Removed header=None so Pandas uses the CSV's first row as the header.

## B – Q2. Data Analysis
Objective: display the **five highest** salaries.
```python
df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})
print(df.sort_values('Salary').head(5))
```

In [11]:
# Corrected code
df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})
print(df.sort_values('Salary',ascending=True).tail(5))


  Employee  Salary
0        A   30000
4        E   45000
1        B   50000
3        D   60000
5        F   70000


**What was wrong and how I fixed it:**

 `sort_values()` sorted salaries in ascending order, so `.head(5)` gave the lowest salaries.

 Used `.tail(5)` after ascending sort to get the **five highest salaries**.


## B – Q3. Cleaning Data
Objective: replace missing marks with the column mean, but the DataFrame is not actually updated.
```python
df = pd.DataFrame({'Marks': [70, None, 90]})
df['Marks'].fillna(df['Marks'].mean())
print(df)
```

In [12]:
# Corrected code
df = pd.DataFrame({'Marks': [70, None, 90]})
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df)

   Marks
0   70.0
1   80.0
2   90.0


**What was wrong and how I fixed it:**

fillna() result was not stored in the DataFrame.

Assigned the filled values back using df['Marks'] 

## B – Q4. Correlation
Objective: correlation between Hours and Marks.
```python
df = pd.DataFrame({'Hours': [1, 2, 3, 4], 'Marks': [20, 40, 60, 80]})
print(df.corr('Hours', 'Marks'))
```

In [13]:
# Corrected code
df = pd.DataFrame({'Hours': [1, 2, 3, 4], 'Marks': [20, 40, 60, 80]})
print(df['Hours'].corr(df['Marks']))


1.0


**What was wrong and how I fixed it:**

df.corr() does not take two column names like that.

Used .corr() directly between the Hours and Marks columns.

Syntax: df['column1'].corr(df['column2'])

# Section C – Edge Cases (12 marks)

## C – Q1. Broadcasting

In [ ]:
a = np.array([[10], [20], [30]])
b = np.array([[1, 2, 3]])

result = a + b

print(result)
print(result.shape)

**Shapes of a and b:**

Shape of A:  (3, 1) 

Shape of B: (1, 3)

**Predicted output / shape:**

[[11 12 13]

 [21 22 23]

 [31 32 33]]

(3, 3)

(3,3)

**How broadcasting works (and why it differs from adding two 1-D arrays):**

Arithmetic operations on NumPy arrays usually require compatible shapes. Broadcasting allows operations between arrays with different but compatible shapes by automatically expanding their dimensions.


**What happens if b = np.array([1, 2]) and why:**

[[11 12]
 [21 22]
 [31 32]]

 The shapes are compatible through broadcasting, so b is treated as (1, 2) and expanded across the rows of a, producing a (3, 2) result.

In [31]:
# Your code to test the b = np.array([1, 2]) case (use try/except so the notebook doesn't stop)
import numpy as np

a = np.array([[10], [20], [30]])
b = np.array([1, 2])

try:
    result = a + b
    print(result)
    print(result.shape)
except ValueError as e:
    print("Error:", e)


[[11 12]
 [21 22]
 [31 32]]
(3, 2)


## C – Q2. Messy CSV (quoted commas, missing values, mixed date formats)
First create the given `students.csv`:

In [32]:
csv_text = """ID,Name,Date,Marks
101,"Asha, R",2026-09-01,80
102,Ravi,01/09/2026,
103,Neha,2026-09-03,NA
"""
with open("students.csv", "w") as f:
    f.write(csv_text)

In [ ]:
# Given code
df = pd.read_csv("students.csv")

print(df)
print(df.dtypes)

    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026    NaN
2  103     Neha  2026-09-03    NaN
ID         int64
Name      object
Date      object
Marks    float64
dtype: object


**How the quoted comma in "Asha, R" is handled:**

The comma is treated as part of the name because "Asha, R" is enclosed in quotation marks.

**Potential issues with the Date and Marks columns:**

The Date column is stored as object instead of datetime, and the Marks column contains missing values (NaN). These should be handled before performing analysis.

In [38]:
print(df.columns)

Index(['ID', 'Name', 'Date', 'Marks'], dtype='object')


In [45]:
df = pd.read_csv("students.csv")

df['Date'] = pd.to_datetime(df['Date'], format='mixed', dayfirst=True)
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)

    ID     Name       Date  Marks
0  101  Asha, R 2026-09-01   80.0
1  102     Ravi 2026-09-01   80.0
2  103     Neha 2026-09-03   80.0


**Why "NA" should be investigated before treating it as missing:**

NA may represent a missing value, but it could also be a valid text value or code. Therefore, its meaning should be confirmed before replacing or removing it.

## C – Q3. Outliers: mean vs median

In [ ]:
df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())

**Predicted mean and median:**

Mean: 2522500.0
Median: 32500.0


**Effect of the extreme value on the mean:**


The extreme salary of 10,000,000 greatly increases the mean, making it much higher than the other salaries.

**Better statistic for a typical salary, and why:**

Median is better because it is less affected by extreme values and represents the typical salary more accurately.


In [48]:
# Find the record with the highest salary
result = df.loc[df['Salary'].idxmax(), ['Employee', 'Salary']]
print(result)

Employee           D
Salary      10000000
Name: 3, dtype: object


**Why the record should be investigated before removing it:**

The record may be a genuine extreme value rather than an error. It should be verified before removing it to avoid losing valid data.

# Section D – Scenario-Based Questions (8 marks)
## D – Q1. Cleaning the student assessment dataset
First create the dirty dataset file:

In [50]:
csv_text = """Student_ID,Student_Name,Department,Assessment,Marks
S101,Asha,IT,Python,85
S102,Ravi,it,Python,78
S103,Neha,I.T.,Python,92
S104,Karan,HR,Python,
S105,Meera,HR,Python,Absent
S106,Arjun,Finance,Python,0
S107,Priya,finance,Python,67
S108,Rahul,IT,Python,75
S102,Ravi,it,Python,78
S109,Sneha,I.T.,Python,NA
S110,Varun,HR,Python,88 marks
S111,Diya,Finance,Python,91
S112,Aman,IT,Python,
S113,Nisha,HR,Python,64
S114,Kabir,Finance,Python,105
"""
with open("student_assessment_dirty.csv", "w") as f:
    f.write(csv_text)

### Step 1 – Load the CSV and inspect with `head()`, `info()`, `isnull().sum()`

In [55]:
df= pd.read_csv("student_assessment_dirty.csv")
print("FIRST 5 ROWS")
display(df.head())
print("Information about Data")
df.info()
df.isnull().sum()



FIRST 5 ROWS


,Student_ID,Student_Name,Department,Assessment,Marks
0,S101,Asha,IT,Python,85
1,S102,Ravi,it,Python,78
2,S103,Neha,I.T.,Python,92
3,S104,Karan,HR,Python,NaN
4,S105,Meera,HR,Python,Absent


Information about Data
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Student_ID    15 non-null     object
 1   Student_Name  15 non-null     object
 2   Department    15 non-null     object
 3   Assessment    15 non-null     object
 4   Marks         12 non-null     object
dtypes: object(5)
memory usage: 732.0+ bytes


Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           3
dtype: int64

**Explanation (one line):**

### Step 2 – Standardize department names (IT / it / I.T. and Finance / finance)

In [59]:
df['Department'] = df['Department'].replace({
    'it': 'IT',
    'I.T.': 'IT',
    'finance': 'Finance'
})

print(df['Department'])


0          IT
1          IT
2          IT
3          HR
4          HR
5     Finance
6     Finance
7          IT
8          IT
9          IT
10         HR
11    Finance
12         IT
13         HR
14    Finance
Name: Department, dtype: object


**Explanation (one line):** Standardized different spellings of department names into consistent values

### Step 3 – Identify and remove exact duplicate records

In [60]:
df = df.drop_duplicates()
print(df)


   Student_ID Student_Name Department Assessment     Marks
0        S101         Asha         IT     Python        85
1        S102         Ravi         IT     Python        78
2        S103         Neha         IT     Python        92
3        S104        Karan         HR     Python       NaN
4        S105        Meera         HR     Python    Absent
5        S106        Arjun    Finance     Python         0
6        S107        Priya    Finance     Python        67
7        S108        Rahul         IT     Python        75
9        S109        Sneha         IT     Python       NaN
10       S110        Varun         HR     Python  88 marks
11       S111         Diya    Finance     Python        91
12       S112         Aman         IT     Python       NaN
13       S113        Nisha         HR     Python        64
14       S114        Kabir    Finance     Python       105


**Explanation (one line):**

Removes rows that are completely identical, such as the duplicate S102 record.

### Step 4 – Convert Marks to numeric (handle "88 marks", "Absent", "NA", blanks)

In [66]:
df_ = df.copy()

df_['Marks'] = pd.to_numeric(df_['Marks'], errors='coerce')

print(df)

   Student_ID Student_Name Department Assessment  Marks
0        S101         Asha         IT     Python   85.0
1        S102         Ravi         IT     Python   78.0
2        S103         Neha         IT     Python   92.0
3        S104        Karan         HR     Python    NaN
4        S105        Meera         HR     Python    NaN
5        S106        Arjun    Finance     Python    0.0
6        S107        Priya    Finance     Python   67.0
7        S108        Rahul         IT     Python   75.0
9        S109        Sneha         IT     Python    NaN
10       S110        Varun         HR     Python    NaN
11       S111         Diya    Finance     Python   91.0
12       S112         Aman         IT     Python    NaN
13       S113        Nisha         HR     Python   64.0
14       S114        Kabir    Finance     Python  105.0


**Explanation (one line):**

Converted valid marks to numeric values and changed invalid or non-numeric entries such as Absent, NA, blanks, and 88 marks into NaN.

### Step 5 – Investigate missing marks: absent vs. not entered

In [67]:
print(df[df['Marks'].isna()])

   Student_ID Student_Name Department Assessment  Marks
3        S104        Karan         HR     Python    NaN
4        S105        Meera         HR     Python    NaN
9        S109        Sneha         IT     Python    NaN
10       S110        Varun         HR     Python    NaN
12       S112         Aman         IT     Python    NaN


### Step 6 – Identify marks outside 0–100 and decide how to handle them

In [78]:
invalid_marks = df_[(df_['Marks'] < 0) | (df_['Marks'] > 100)]
print(invalid_marks)


   Student_ID Student_Name Department Assessment  Marks
14       S114        Kabir    Finance     Python  105.0


### Step 7 – Display the cleaned DataFrame and report: records removed, missing marks remaining, invalid marks identified

In [79]:
print("Cleaned DataFrame:")
print(df)

print("\nCleaning Report")
print("Records removed:", 15 - len(df))
print("Missing marks remaining:", df['Marks'].isna().sum())

invalid_marks = df[(df['Marks'] < 0) | (df['Marks'] > 100)]
print("Invalid marks identified:", len(invalid_marks))

Cleaned DataFrame:
   Student_ID Student_Name Department Assessment  Marks
0        S101         Asha         IT     Python   85.0
1        S102         Ravi         IT     Python   78.0
2        S103         Neha         IT     Python   92.0
3        S104        Karan         HR     Python    NaN
4        S105        Meera         HR     Python    NaN
5        S106        Arjun    Finance     Python    0.0
6        S107        Priya    Finance     Python   67.0
7        S108        Rahul         IT     Python   75.0
9        S109        Sneha         IT     Python    NaN
10       S110        Varun         HR     Python    NaN
11       S111         Diya    Finance     Python   91.0
12       S112         Aman         IT     Python    NaN
13       S113        Nisha         HR     Python   64.0
14       S114        Kabir    Finance     Python    NaN

Cleaning Report
Records removed: 1
Missing marks remaining: 6
Invalid marks identified: 0


**Explanation (one line):**

The code displays the cleaned DataFrame and reports the number of records removed, missing marks remaining, and marks outside the valid 0–100 range.

### Risk of deleting missing values without investigating why they are missing
**Your answer:**

Deleting missing values without investigating their cause can remove valid information, such as students who were absent, and may lead to inaccurate analysis.